In [1]:
# 문제1 : 배열 생성 및 변형
# 1부터 25까지의 숫자를 포함하는 1차원 배열을 만든 후, 이 배열을 5x5 크기의 2차원 배열로 변형하세요.

import numpy as np

# 1. 1부터 25까지의 숫자를 포함하는 1차원 배열 생성
# np.arange(시작, 끝+1) 함수를 사용합니다.
array_1d = np.arange(1, 26)
print("--- 1차원 배열 ---")
print(array_1d)
print() # 줄바꿈

# 2. 1차원 배열을 5x5 크기의 2차원 배열로 변형
# .reshape(행, 열) 메서드를 사용합니다.
array_2d = array_1d.reshape(5, 5)
print("--- 5x5 2차원 배열 ---")
print(array_2d)

--- 1차원 배열 ---
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]

--- 5x5 2차원 배열 ---
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [2]:
# 문제2 : 배열 슬라이싱
# 위 1번 문제에서 생성한 5x5 배열에서, 아래 그림과 같이 안쪽에 위치한 3x3 배열(값 7부터 19까지)을 슬라이싱하여 추출하세요.

import numpy as np

# 1번 문제의 5x5 배열을 먼저 생성합니다.
array_2d = np.arange(1, 26).reshape(5, 5)

# 배열 슬라이싱을 사용하여 3x3 부분을 추출합니다.
# array[행_시작:행_끝, 열_시작:열_끝]
# 행은 1번 인덱스부터 3번 인덱스까지 (4 직전까지)
# 열은 1번 인덱스부터 3번 인덱스까지 (4 직전까지)
inner_array = array_2d[1:4, 1:4]

print("--- 원본 5x5 배열 ---")
print(array_2d)
print()
print("--- 추출된 3x3 배열 ---")
print(inner_array)

--- 원본 5x5 배열 ---
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

--- 추출된 3x3 배열 ---
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [3]:
# 문제3 : 브로드캐스팅 활용 연산
# 2x3 크기의 배열 `A = np.array([[5, 10, 15], [20, 25, 30]])`가 있습니다. 이 배열의 첫 번째 행에는 100을, 두 번째 행에는 200을 더하세요. 브로드캐스팅을 활용하여 한 줄의 코드로 해결해 보세요.
# (힌트: `[[100], [200]]` 형태의 배열을 더해야 합니다.)

import numpy as np

# 2x3 크기의 배열 A를 생성합니다.
A = np.array([[5, 10, 15], [20, 25, 30]])

# 더할 값을 담은 (2, 1) 크기의 배열 B를 생성합니다.
# A(2, 3)와 B(2, 1)의 shape이 다르지만, 브로드캐스팅 규칙에 따라 연산이 가능합니다.
# B의 열(column)이 A의 열 개수에 맞게 확장(stretch)되어 각 행에 더해집니다.
# [[100], [200]] -> [[100, 100, 100], [200, 200, 200]] 으로 확장되어 계산됩니다.
B = np.array([[100], [200]])

# 브로드캐스팅을 활용한 연산 (한 줄 코드)
result = A + B

print("--- 원본 배열 A ---")
print(A)
print()
print("--- 더하는 배열 B ---")
print(B)
print()
print("--- 브로드캐스팅 연산 결과 ---")
print(result)

--- 원본 배열 A ---
[[ 5 10 15]
 [20 25 30]]

--- 더하는 배열 B ---
[[100]
 [200]]

--- 브로드캐스팅 연산 결과 ---
[[105 110 115]
 [220 225 230]]


In [4]:
# 문제4 : 불리언 인덱싱 (필터링)
# 0부터 15까지의 숫자를 가진 4x4 배열을 만드세요. 이 배열에서 3의 배수만 모두 추출하여 1차원 배열로 만드세요.

import numpy as np

# 1. 0부터 15까지의 숫자를 가진 4x4 배열 생성
array_4x4 = np.arange(16).reshape(4, 4)

# 2. 불리언 인덱싱을 위한 조건 생성
# 배열의 각 요소를 3으로 나누었을 때 나머지가 0인 경우 True, 아니면 False가 되는
# 조건 배열(불리언 마스크)을 만듭니다.
condition = array_4x4 % 3 == 0

# 3. 조건(condition)을 사용하여 3의 배수만 추출
# 원본 배열에 조건 배열을 인덱스로 전달하면,
# True에 해당하는 위치의 요소들만 추출되어 새로운 1차원 배열로 반환됩니다.
multiples_of_3 = array_4x4[condition]

print("--- 원본 4x4 배열 ---")
print(array_4x4)
print()
print("--- 3의 배수 조건 배열 (불리언 마스크) ---")
print(condition)
print()
print("--- 추출된 3의 배수 (1차원 배열) ---")
print(multiples_of_3)

--- 원본 4x4 배열 ---
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

--- 3의 배수 조건 배열 (불리언 마스크) ---
[[ True False False  True]
 [False False  True False]
 [False  True False False]
 [ True False False  True]]

--- 추출된 3의 배수 (1차원 배열) ---
[ 0  3  6  9 12 15]


In [5]:
# 문제5 : 통계 연산 (축 기준)
# 다음은 4일간 3개 상점의 일일 매출 데이터입니다.
# `sales = np.array([[50, 60, 55], [80, 95, 75], [40, 100, 90], [70, 85, 80]])`
# 각 상점별(열 기준) 평균 매출과 각 날짜별(행 기준) 총매출을 각각 계산하세요.

import numpy as np

# 4일간 3개 상점의 일일 매출 데이터
sales = np.array([[50, 60, 55],
                  [80, 95, 75],
                  [40, 100, 90],
                  [70, 85, 80]])

# 1. 각 상점별(열 기준) 평균 매출 계산 (axis=0)
store_avg_sales = sales.mean(axis=0)

# 2. 각 날짜별(행 기준) 총 매출 계산 (axis=1)
daily_total_sales = sales.sum(axis=1)

print("--- 원본 매출 데이터 ---")
print(sales)
print("\n--- 각 상점별 평균 매출 ---")
print(store_avg_sales)
print("\n--- 각 날짜별 총 매출 ---")
print(daily_total_sales)

--- 원본 매출 데이터 ---
[[ 50  60  55]
 [ 80  95  75]
 [ 40 100  90]
 [ 70  85  80]]

--- 각 상점별 평균 매출 ---
[60. 85. 75.]

--- 각 날짜별 총 매출 ---
[165 250 230 235]


In [6]:
# 문제 6: `np.where` 활용
# 1부터 10까지의 숫자를 가진 배열에서, 5보다 큰 숫자는 제곱하고, 5보다 작거나 같은 숫자는 0으로 바꾸는 새로운 배열을 생성하세요.

import numpy as np

# 1. 1부터 10까지의 숫자를 가진 배열 생성
original_array = np.arange(1, 11)

# 2. np.where를 사용하여 조건에 따라 새로운 배열 생성
# np.where(조건, 참일 때 적용할 값, 거짓일 때 적용할 값)
#
# 조건: original_array > 5
# 참일 때: 원본 배열의 요소를 제곱 (original_array**2)
# 거짓일 때: 0
new_array = np.where(original_array > 5, original_array**2, 0)

print("--- 원본 배열 ---")
print(original_array)
print()
print("--- np.where 적용 후 새로운 배열 ---")
print(new_array)

--- 원본 배열 ---
[ 1  2  3  4  5  6  7  8  9 10]

--- np.where 적용 후 새로운 배열 ---
[  0   0   0   0   0  36  49  64  81 100]


In [7]:
# 문제 7: `argmax` 활용
# 어떤 선수의 주간 득점 기록이 `scores = np.array([12, 25, 8, 31, 19, 22, 15])`와 같습니다. 이 선수가 가장 높은 득점을 기록한 것은 몇 번째 주(week)인지 찾아내세요. (인덱스는 0부터 시작)

import numpy as np

# 선수의 주간 득점 기록 (1주차, 2주차, ...)
scores = np.array([12, 25, 8, 31, 19, 22, 15])

# np.argmax() 함수는 배열에서 가장 큰 값의 첫 번째 인덱스를 반환합니다.
# 이 인덱스가 가장 높은 득점을 기록한 주(week)가 됩니다.
hottest_week_index = np.argmax(scores)

# (참고) 가장 높은 점수 자체를 찾으려면 np.max() 또는 scores.max()를 사용합니다.
max_score = np.max(scores)

print("--- 주간 득점 기록 ---")
print(scores)
print()
print(f"가장 높은 득점: {max_score}")
print(f"가장 높은 득점을 기록한 주(인덱스): {hottest_week_index}")

# 인덱스는 0부터 시작하므로, 실제로는 (인덱스 + 1)번째 주입니다.
print(f"따라서, 선수는 {hottest_week_index + 1}번째 주에 가장 높은 득점을 기록했습니다.")

--- 주간 득점 기록 ---
[12 25  8 31 19 22 15]

가장 높은 득점: 31
가장 높은 득점을 기록한 주(인덱스): 3
따라서, 선수는 4번째 주에 가장 높은 득점을 기록했습니다.


In [8]:
# 문제 8: 배열 합치기
# `a = np.array([[1, 2], [3, 4]])`와 `b = np.array([[5, 6]])`가 있습니다. `b`를 `a`의 아래에 수직으로 붙여서 3x2 배열을 만드세요.

import numpy as np

# 2x2 배열 a
a = np.array([[1, 2], [3, 4]])

# 1x2 배열 b
b = np.array([[5, 6]])

# np.vstack() 함수를 사용하여 배열들을 수직으로(vertically) 쌓습니다.
# vstack에 튜플 형태로 쌓을 배열들을 전달합니다: (a, b)
# a와 b의 열의 개수가 같아야 합니다.
c = np.vstack((a, b))

# 참고: np.concatenate((a, b), axis=0) 와 동일하게 동작합니다.

print("--- 배열 a ---")
print(a)
print()
print("--- 배열 b ---")
print(b)
print()
print("--- 수직으로 합친 배열 c ---")
print(c)
print()
print(f"합쳐진 배열의 shape: {c.shape}")

--- 배열 a ---
[[1 2]
 [3 4]]

--- 배열 b ---
[[5 6]]

--- 수직으로 합친 배열 c ---
[[1 2]
 [3 4]
 [5 6]]

합쳐진 배열의 shape: (3, 2)


In [9]:
# 문제 9: 결측치(NaN) 처리
# 다음 배열에서 결측치(`np.nan`)의 개수를 세고, 결측치를 해당 배열의 전체 평균값(결측치를 제외한)으로 대체하세요.
# `data = np.array([10., 20., np.nan, 30., 40., np.nan, 50.])`

import numpy as np

# 결측치가 포함된 배열
data = np.array([10., 20., np.nan, 30., 40., np.nan, 50.])
print("--- 원본 배열 ---")
print(data)
print()

# 1. 결측치(NaN) 개수 세기
# np.isnan()은 NaN 위치에 True를, 아닌 곳에 False를 갖는 불리언 배열을 반환합니다.
# 불리언 배열에 np.sum()을 적용하면 True의 개수(즉, NaN의 개수)를 셀 수 있습니다.
nan_count = np.sum(np.isnan(data))
print(f"결측치(NaN)의 개수: {nan_count}")
print()

# 2. 결측치를 평균값으로 대체하기
# np.nanmean() 함수는 배열 내의 NaN 값을 무시하고 평균을 계산합니다.
mean_val = np.nanmean(data)
print(f"결측치를 제외한 평균값: {mean_val}")
print()

# np.isnan(data)를 사용해 NaN인 위치를 찾아, 그 위치의 값들을 위에서 구한 평균값으로 대입(대체)합니다.
data[np.isnan(data)] = mean_val

print("--- 결측치 대체 후 배열 ---")
print(data)

--- 원본 배열 ---
[10. 20. nan 30. 40. nan 50.]

결측치(NaN)의 개수: 2

결측치를 제외한 평균값: 30.0

--- 결측치 대체 후 배열 ---
[10. 20. 30. 30. 40. 30. 50.]


In [11]:
# 문제 10: 종합 응용
# 10x2 크기의 배열에 0부터 99까지의 정수를 무작위로 채우세요. 이 배열은 (x, y) 좌표 목록으로 간주합니다. 이 중에서 x값(0번 열)이 y값(1번 열)보다 큰 모든 좌표(행)를 찾아 출력하세요.

import numpy as np

# 1. 10x2 크기의 배열에 0~99 사이의 정수를 무작위로 채웁니다.
# np.random.randint(최소값, 최대값+1, size=(행, 열))
# 실행할 때마다 다른 랜덤 값으로 채워집니다.
coords = np.random.randint(0, 100, size=(10, 2))
print("--- 전체 (x, y) 좌표 배열 ---")
print(coords)
print()

# 2. x > y 인 조건을 만듭니다.
# 0번 열(x 좌표)이 1번 열(y 좌표)보다 큰 행을 찾습니다.
# 이 조건은 각 행에 대해 True 또는 False를 갖는 1차원 불리언 배열을 생성합니다.
condition = coords[:, 0] > coords[:, 1]

# 3. 불리언 인덱싱으로 조건에 맞는 행만 추출합니다.
# coords 배열에 위에서 만든 condition 배열을 인덱스로 전달하면,
# condition이 True인 행들만 선택되어 새로운 배열로 반환됩니다.
result_coords = coords[condition]

print("--- x값이 y값보다 큰 좌표들 ---")
print(result_coords)

--- 전체 (x, y) 좌표 배열 ---
[[39  2]
 [28  8]
 [ 8 49]
 [94 96]
 [44 19]
 [70 89]
 [35 61]
 [58 25]
 [45  5]
 [97 46]]

--- x값이 y값보다 큰 좌표들 ---
[[39  2]
 [28  8]
 [44 19]
 [58 25]
 [45  5]
 [97 46]]
